all:
	mkdir -p ./resources/usr/bin/
	curl -L https://github.com/dnanexus/dxfuse/releases/latest/download/dxfuse-linux > ./resources/usr/bin/dxfuse
	echo msg 1
	ls -l ./resources/usr/bin
	echo msg 2
	chmod +x ./resources/usr/bin/dxfuse
	echo msg 3
	ls -l ./resources/usr/bin
	echo msg 4
