#!/usr/bin/env python
#
# Copyright (C) 2013-2014 DNAnexus, Inc.
#
# This file is part of dx-toolkit (DNAnexus platform client libraries).
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may not
#   use this file except in compliance with the License. You may obtain a copy
#   of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

import os, sys, json, argparse, subprocess
import pprint

import dxpy
import dxpy.utils

## contains specific helper functions
from dxpy.utils import file_load_utils


'''
create a set of directories, so we could store the input files.
For example, seq1 could be stored under:
   /out/seq1/NC_001122.fasta

TODO: this call could fail, we need to report a reasonable error code
'''
def create_dirs(idir, dirs):
    print ("create_dirs " + str(len(dirs)))
    if len(dirs) == 0:
        return
    ## create the <idir> itself
    file_load_utils.ensure_dir(idir)
    ## create each subdir
    for d in dirs:
        file_load_utils.ensure_dir(os.path.join(idir, d))

## entry point
##

## parse the command line
##
## exclude -- a list of arguments to skip over
parser = argparse.ArgumentParser(description='Download all the files as described in the input json file')
parser.add_argument('--except', 
                    help='Do not download this argument',
                    action="append",
                    dest="exclude")
args = parser.parse_args()

## input directory, where all inputs are downloaded
idir = file_load_utils.get_input_dir();
dirs, inputs = file_load_utils.parse_job_input(idir)
#pp = pprint.PrettyPrinter(indent=4)
#pp.pprint(inputs)
#pp.pprint(dirs)

## Create the directory structure, in preparation for download.
## Allows performing the download in parallel.
create_dirs(idir, dirs)

## Remove from the excluded records
to_download = []
if args.exclude == None:
    to_download = inputs
else:
    for rec in inputs:
        if not rec['iname'] in args.exclude:
            to_download.append(rec)

## Download the files, currently, this is done sequentially (one file at 
## a time).
for rec in to_download:
    print("download file: " + rec['src_file_id'] + "-> " + rec['trg_fname'])
    dxpy.download_dxfile(rec['src_file_id'], rec['trg_fname'])




