#!/usr/bin/env python

import sys, json, argparse

parser = argparse.ArgumentParser(description='Parse a dxlink JSON hash into an object ID or project:object-id tuple')
parser.add_argument('dxlink', help='Link to parse')
parser.add_argument('--no-project', help='Ignore project ID in an extended dxlink - just print the object ID', action='store_true')
args = parser.parse_args()

try:
    link = json.loads(args.dxlink)['$dnanexus_link']
except KeyError:
    parser.exit("Unable to parse link: no $dnanexus_link key")
except ValueError:
    parser.exit("Unable to parse link as JSON")

if isinstance(link, dict):
    print "{proj}:{obj}".format(proj=link['project'], obj=link['id'])
else:
    print link
