#!/usr/bin/env python

import dxpy
import math
import operator
import argparse
import re

#Example: dx_writeReferenceIndex --contig_set record-9yZvF200000PYKJyV4k00005 --writeSamtoolsIndex ref.fa.fai --writePicardDictionary ref.dict

def main():

    parser = argparse.ArgumentParser(description='Extract chromosome information from a ContigSet record on the DNAnexus platform and create the requested reference index files locally.')
    parser.add_argument("--contig_set", dest="contig_set", help="ContigSet to extract chromosome information from")
    parser.add_argument("--writeSamtoolsIndex", dest="samtools", help="Write .fa.fai file to this file name")
    parser.add_argument("--writePicardDictionary", dest="picard", help="Write .dict file to this file name")

    args = parser.parse_args()

    if args.samtools is not None:
        writeReferenceIndex(args.contig_set, args.samtools)
    if args.picard is not None:
        writeGenomeDict(args.contig_set, args.picard)


def writeGenomeDict(contig_set, dictFileName):
    print contig_set
    details = dxpy.DXRecord(contig_set).get_details()
    sizes = details['contigs']['sizes']
    names = details['contigs']['names']

    dictFile = open(dictFileName, 'w')
    dictFile.write("@HD\tVN:1.0\tSN:unsorted\n")
    for i in range(len(sizes)):
        line = "@SQ\tSN:%s\tLN:%s\n" % (names[i], str(sizes[i]))
        dictFile.write(line)
    return

def writeReferenceIndex(contig_set, indexFileName):
    details = dxpy.DXRecord(contig_set).get_details()
    sizes = details['contigs']['sizes']
    names = details['contigs']['names']
    
    dictFile = open(indexFileName, 'w')
    priorOffset = 0
    priorLength = 0
    first = True
    for i in range(len(names)):
        offset = priorOffset + len(names[i])+ 2 + priorLength + math.ceil(float(priorLength)/60.0)
        if first:
            first = False
        else:
            offset += 1
        dictFile.write(names[i]+"\t"+str(sizes[i]) + "\t" + str(int(offset)) + "\t60\t61\n")
        priorOffset = offset
        priorLength = sizes[i]
    return

main()
