#!/usr/bin/env python
# DX_APP_WIZARD_NAME DX_APP_WIZARD_VERSION
# Generated by dx-app-wizard.
# See http://wiki.dnanexus.com/Building-Your-First-DNAnexus-App for
# instructions on how to modify this file.

import os
import dxpy

@dxpy.entry_point('main')
def main(DX_APP_WIZARD_INPUT):
DX_APP_WIZARD_FILE_INPUT
    # Fill in your application code here.  Dummy output provided
    # below.

    return DX_APP_WIZARD_OUTPUT

dxpy.run()
