simplehttplib = ./SimpleHttpLib
all:
	(cd dxcpp; mkdir build; cd build; cmake ..; make)
	(cd SimpleHttpLib; mkdir build; cd build; cmake ..; make)

clean:
	(cd dxcpp; rm -rf build)
	(cd SimpleHttpLib; rm -rf build)
