# Do not modify this file by hand.
#
# It is automatically generated by src/api_wrappers/generateRubyAPIWrappers.py.
# (Run make api_wrappers to update it.)

require 'dxruby'

module DX
  module API
    # Invokes the /analysis-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-analysis-xxxx-addtags
    def self.analysis_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /analysis-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-analysis-xxxx-describe
    def self.analysis_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /analysis-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-analysis-xxxx-removetags
    def self.analysis_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /analysis-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-analysis-xxxx-setproperties
    def self.analysis_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /analysis-xxxx/terminate API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-analysis-xxxx-terminate
    def self.analysis_terminate(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/terminate", input_params, opts)
    end

    # Invokes the /app-xxxx/addAuthorizedUsers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-addauthorizedusers
    def self.app_add_authorized_users(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/addAuthorizedUsers", input_params, opts)
    end

    # Invokes the /app-xxxx/addCategories API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-addcategories
    def self.app_add_categories(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/addCategories", input_params, opts)
    end

    # Invokes the /app-xxxx/addDevelopers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-adddevelopers
    def self.app_add_developers(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/addDevelopers", input_params, opts)
    end

    # Invokes the /app-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-addtags
    def self.app_add_tags(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/addTags", input_params, opts)
    end

    # Invokes the /app-xxxx/delete API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-delete
    def self.app_delete(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/delete", input_params, opts)
    end

    # Invokes the /app-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-describe
    def self.app_describe(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/describe", input_params, opts)
    end

    # Invokes the /app-xxxx/get API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-get
    def self.app_get(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/get", input_params, opts)
    end

    # Invokes the /app-xxxx/install API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-install
    def self.app_install(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/install", input_params, opts)
    end

    # Invokes the /app-xxxx/listAuthorizedUsers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-listauthorizedusers
    def self.app_list_authorized_users(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/listAuthorizedUsers", input_params, opts)
    end

    # Invokes the /app-xxxx/listCategories API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-listcategories
    def self.app_list_categories(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/listCategories", input_params, opts)
    end

    # Invokes the /app-xxxx/listDevelopers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-listdevelopers
    def self.app_list_developers(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/listDevelopers", input_params, opts)
    end

    # Invokes the /app-xxxx/publish API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-publish
    def self.app_publish(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/publish", input_params, opts)
    end

    # Invokes the /app-xxxx/removeAuthorizedUsers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-removeauthorizedusers
    def self.app_remove_authorized_users(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/removeAuthorizedUsers", input_params, opts)
    end

    # Invokes the /app-xxxx/removeCategories API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-removecategories
    def self.app_remove_categories(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/removeCategories", input_params, opts)
    end

    # Invokes the /app-xxxx/removeDevelopers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-removedevelopers
    def self.app_remove_developers(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/removeDevelopers", input_params, opts)
    end

    # Invokes the /app-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-removetags
    def self.app_remove_tags(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/removeTags", input_params, opts)
    end

    # Invokes the /app-xxxx/run API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-run
    def self.app_run(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/run", input_params, opts)
    end

    # Invokes the /app-xxxx/validateBatch API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-validatebatch
    def self.app_validate_batch(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/validateBatch", input_params, opts)
    end

    # Invokes the /app-xxxx/uninstall API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-uninstall
    def self.app_uninstall(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/uninstall", input_params, opts)
    end

    # Invokes the /app-xxxx/update API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-xxxx-yyyy-update
    def self.app_update(app_name_or_id, app_alias=nil, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      fully_qualified_version = app_name_or_id + (app_alias ? ('/' + app_alias) : '')
      return DX::http_request("/#{fully_qualified_version}/update", input_params, opts)
    end

    # Invokes the /app/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/apps#api-method-app-new
    def self.app_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/app/new", input_params, opts)
    end

    # Invokes the /applet-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-addtags
    def self.applet_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /applet-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-applet-xxxx-describe
    def self.applet_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /applet-xxxx/get API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-applet-xxxx-get
    def self.applet_get(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/get", input_params, opts)
    end

    # Invokes the /applet-xxxx/getDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-getdetails
    def self.applet_get_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/getDetails", input_params, opts)
    end

    # Invokes the /applet-xxxx/listProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-listprojects
    def self.applet_list_projects(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listProjects", input_params, opts)
    end

    # Invokes the /applet-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-removetags
    def self.applet_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /applet-xxxx/rename API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/name#api-method-class-xxxx-rename
    def self.applet_rename(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/rename", input_params, opts)
    end

    # Invokes the /applet-xxxx/validateBatch API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-applet-xxxx-validatebatch
    def self.applet_validate_batch(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/validateBatch", input_params, opts)
    end

    # Invokes the /applet-xxxx/run API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-applet-xxxx-run
    def self.applet_run(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/run", input_params, opts)
    end

    # Invokes the /applet-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/properties#api-method-class-xxxx-setproperties
    def self.applet_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /applet/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-applet-new
    def self.applet_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/applet/new", input_params, opts)
    end

    # Invokes the /container-xxxx/clone API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-clone
    def self.container_clone(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/clone", input_params, opts)
    end

    # Invokes the /container-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/containers-for-execution#api-method-container-xxxx-describe
    def self.container_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /container-xxxx/destroy API method.
    def self.container_destroy(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/destroy", input_params, opts)
    end

    # Invokes the /container-xxxx/listFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-listfolder
    def self.container_list_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listFolder", input_params, opts)
    end

    # Invokes the /container-xxxx/move API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-move
    def self.container_move(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/move", input_params, opts)
    end

    # Invokes the /container-xxxx/newFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-newfolder
    def self.container_new_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/newFolder", input_params, opts)
    end

    # Invokes the /container-xxxx/removeFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-removefolder
    def self.container_remove_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/removeFolder", input_params, opts)
    end

    # Invokes the /container-xxxx/removeObjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-removeobjects
    def self.container_remove_objects(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/removeObjects", input_params, opts)
    end

    # Invokes the /container-xxxx/renameFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-renamefolder
    def self.container_rename_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/renameFolder", input_params, opts)
    end

    # Invokes the /database-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-addtags
    def self.database_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /database-xxxx/addTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-addtypes
    def self.database_add_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTypes", input_params, opts)
    end

    # Invokes the /database-xxxx/close API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle#api-method-class-xxxx-close
    def self.database_close(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/close", input_params, opts)
    end

    # Invokes the /database-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/databases#api-method-database-xxxx-describe
    def self.database_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /database-xxxx/getDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-getdetails
    def self.database_get_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/getDetails", input_params, opts)
    end

    # Invokes the /database-xxxx/listProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-listprojects
    def self.database_list_projects(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listProjects", input_params, opts)
    end

    # Invokes the /database-xxxx/relocate API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/databases#api-method-database-xxxx-relocate
    def self.database_relocate(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/relocate", input_params, opts)
    end

    # Invokes the /database-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-removetags
    def self.database_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /database-xxxx/removeTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-removetypes
    def self.database_remove_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTypes", input_params, opts)
    end

    # Invokes the /database-xxxx/rename API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/name#api-method-class-xxxx-rename
    def self.database_rename(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/rename", input_params, opts)
    end

    # Invokes the /database-xxxx/setDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-setdetails
    def self.database_set_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setDetails", input_params, opts)
    end

    # Invokes the /database-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/properties#api-method-class-xxxx-setproperties
    def self.database_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /database-xxxx/setVisibility API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/visibility#api-method-class-xxxx-setvisibility
    def self.database_set_visibility(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setVisibility", input_params, opts)
    end

    # Invokes the /database-xxxx/downloadFile API method.
    def self.database_download_file(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/downloadFile", input_params, opts)
    end

    # Invokes the /database-xxxx/listFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-listfolder
    def self.database_list_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listFolder", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-addtags
    def self.dbcluster_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/addTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-addtypes
    def self.dbcluster_add_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTypes", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/dbclusters#api-method-dbcluster-xxxx-describe
    def self.dbcluster_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/getDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-getdetails
    def self.dbcluster_get_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/getDetails", input_params, opts)
    end

    # Invokes the /dbcluster/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/dbclusters#api-method-dbcluster-new
    def self.dbcluster_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/dbcluster/new", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-removetags
    def self.dbcluster_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/removeTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-removetypes
    def self.dbcluster_remove_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTypes", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/rename API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/name#api-method-class-xxxx-rename
    def self.dbcluster_rename(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/rename", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/setDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-setdetails
    def self.dbcluster_set_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setDetails", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/properties#api-method-class-xxxx-setproperties
    def self.dbcluster_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/setVisibility API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/visibility#api-method-class-xxxx-setvisibility
    def self.dbcluster_set_visibility(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setVisibility", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/start API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/dbclusters#api-method-dbcluster-xxxx-start
    def self.dbcluster_start(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/start", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/stop API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/dbclusters#api-method-dbcluster-xxxx-stop
    def self.dbcluster_stop(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/stop", input_params, opts)
    end

    # Invokes the /dbcluster-xxxx/terminate API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/dbclusters#api-method-dbcluster-xxxx-terminate
    def self.dbcluster_terminate(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/terminate", input_params, opts)
    end

    # Invokes the /file-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-addtags
    def self.file_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /file-xxxx/addTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-addtypes
    def self.file_add_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTypes", input_params, opts)
    end

    # Invokes the /file-xxxx/close API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/files#api-method-file-xxxx-close
    def self.file_close(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/close", input_params, opts)
    end

    # Invokes the /file-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/files#api-method-file-xxxx-describe
    def self.file_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /file-xxxx/download API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/files#api-method-file-xxxx-download
    def self.file_download(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/download", input_params, opts)
    end

    # Invokes the /file-xxxx/getDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-getdetails
    def self.file_get_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/getDetails", input_params, opts)
    end

    # Invokes the /file-xxxx/listProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-listprojects
    def self.file_list_projects(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listProjects", input_params, opts)
    end

    # Invokes the /file-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-removetags
    def self.file_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /file-xxxx/removeTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-removetypes
    def self.file_remove_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTypes", input_params, opts)
    end

    # Invokes the /file-xxxx/rename API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/name#api-method-class-xxxx-rename
    def self.file_rename(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/rename", input_params, opts)
    end

    # Invokes the /file-xxxx/setDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-setdetails
    def self.file_set_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setDetails", input_params, opts)
    end

    # Invokes the /file-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/properties#api-method-class-xxxx-setproperties
    def self.file_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /file-xxxx/setVisibility API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/visibility#api-method-class-xxxx-setvisibility
    def self.file_set_visibility(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setVisibility", input_params, opts)
    end

    # Invokes the /file-xxxx/upload API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/files#api-method-file-xxxx-upload
    def self.file_upload(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/upload", input_params, opts)
    end

    # Invokes the /file/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/files#api-method-file-new
    def self.file_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/file/new", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/addAuthorizedUsers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-addauthorizedusers
    def self.global_workflow_add_authorized_users(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addAuthorizedUsers", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/addCategories API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-addcategories
    def self.global_workflow_add_categories(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addCategories", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/addDevelopers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-adddevelopers
    def self.global_workflow_add_developers(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addDevelopers", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-addtags
    def self.global_workflow_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/delete API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-delete
    def self.global_workflow_delete(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/delete", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-describe
    def self.global_workflow_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/listAuthorizedUsers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-listauthorizedusers
    def self.global_workflow_list_authorized_users(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listAuthorizedUsers", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/listCategories API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-listcategories
    def self.global_workflow_list_categories(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listCategories", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/listDevelopers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-listdevelopers
    def self.global_workflow_list_developers(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listDevelopers", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/publish API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-publish
    def self.global_workflow_publish(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/publish", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/removeAuthorizedUsers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-removeauthorizedusers
    def self.global_workflow_remove_authorized_users(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeAuthorizedUsers", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/removeCategories API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-removecategories
    def self.global_workflow_remove_categories(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeCategories", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/removeDevelopers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-removedevelopers
    def self.global_workflow_remove_developers(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeDevelopers", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-removetags
    def self.global_workflow_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/run API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-run
    def self.global_workflow_run(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/run", input_params, opts)
    end

    # Invokes the /globalworkflow-xxxx/update API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-update
    def self.global_workflow_update(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/update", input_params, opts)
    end

    # Invokes the /globalworkflow/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-new
    def self.global_workflow_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/globalworkflow/new", input_params, opts)
    end

    # Invokes the /job-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-xxxx-addtags
    def self.job_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /job-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-xxxx-describe
    def self.job_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /job-xxxx/getLog API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-xxxx-getlog
    def self.job_get_log(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/getLog", input_params, opts)
    end

    # Invokes the /job-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-xxxx-removetags
    def self.job_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /job-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-xxxx-setproperties
    def self.job_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /job-xxxx/terminate API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-xxxx-terminate
    def self.job_terminate(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/terminate", input_params, opts)
    end

    # Invokes the /job-xxxx/update API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-xxxx-update
    def self.job_update(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/update", input_params, opts)
    end

    # Invokes the /job/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/applets-and-entry-points#api-method-job-new
    def self.job_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/job/new", input_params, opts)
    end

    # Invokes the /notifications/get API method.
    def self.notifications_get(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/notifications/get", input_params, opts)
    end

    # Invokes the /notifications/markRead API method.
    def self.notifications_mark_read(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/notifications/markRead", input_params, opts)
    end

    # Invokes the /org-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-describe
    def self.org_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /org-xxxx/findMembers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-findmembers
    def self.org_find_members(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/findMembers", input_params, opts)
    end

    # Invokes the /org-xxxx/findProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-findprojects
    def self.org_find_projects(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/findProjects", input_params, opts)
    end

    # Invokes the /org-xxxx/findApps API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-findapps
    def self.org_find_apps(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/findApps", input_params, opts)
    end

    # Invokes the /org-xxxx/invite API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-invite
    def self.org_invite(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/invite", input_params, opts)
    end

    # Invokes the /org-xxxx/removeMember API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-removemember
    def self.org_remove_member(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeMember", input_params, opts)
    end

    # Invokes the /org-xxxx/setMemberAccess API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-setmemberaccess
    def self.org_set_member_access(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setMemberAccess", input_params, opts)
    end

    # Invokes the /org-xxxx/update API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-xxxx-update
    def self.org_update(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/update", input_params, opts)
    end

    # Invokes the /org/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/organizations#api-method-org-new
    def self.org_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/org/new", input_params, opts)
    end

    # Invokes the /project-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-addtags
    def self.project_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /project-xxxx/archive API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-archive
    def self.project_archive(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/archive", input_params, opts)
    end

    # Invokes the /project-xxxx/unarchive API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-unarchive
    def self.project_unarchive(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/unarchive", input_params, opts)
    end

    # Invokes the /project-xxxx/clone API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-clone
    def self.project_clone(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/clone", input_params, opts)
    end

    # Invokes the /project-xxxx/decreasePermissions API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/project-permissions-and-sharing#api-method-project-xxxx-decreasepermissions
    def self.project_decrease_permissions(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/decreasePermissions", input_params, opts)
    end

    # Invokes the /project-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-describe
    def self.project_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /project-xxxx/destroy API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-destroy
    def self.project_destroy(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/destroy", input_params, opts)
    end

    # Invokes the /project-xxxx/invite API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/project-permissions-and-sharing#api-method-project-xxxx-invite
    def self.project_invite(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/invite", input_params, opts)
    end

    # Invokes the /project-xxxx/leave API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/project-permissions-and-sharing#api-method-project-xxxx-leave
    def self.project_leave(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/leave", input_params, opts)
    end

    # Invokes the /project-xxxx/listFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-listfolder
    def self.project_list_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listFolder", input_params, opts)
    end

    # Invokes the /project-xxxx/move API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-move
    def self.project_move(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/move", input_params, opts)
    end

    # Invokes the /project-xxxx/newFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-newfolder
    def self.project_new_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/newFolder", input_params, opts)
    end

    # Invokes the /project-xxxx/removeFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-removefolder
    def self.project_remove_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/removeFolder", input_params, opts)
    end

    # Invokes the /project-xxxx/removeObjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-removeobjects
    def self.project_remove_objects(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/removeObjects", input_params, opts)
    end

    # Invokes the /project-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-removetags
    def self.project_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /project-xxxx/renameFolder API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/folders-and-deletion#api-method-class-xxxx-renamefolder
    def self.project_rename_folder(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/renameFolder", input_params, opts)
    end

    # Invokes the /project-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-setproperties
    def self.project_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /project-xxxx/transfer API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/project-permissions-and-sharing#api-method-project-xxxx-transfer
    def self.project_transfer(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/transfer", input_params, opts)
    end

    # Invokes the /project-xxxx/update API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-update
    def self.project_update(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/update", input_params, opts)
    end

    # Invokes the /project-xxxx/updateSponsorship API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-xxxx-updatesponsorship
    def self.project_update_sponsorship(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/updateSponsorship", input_params, opts)
    end

    # Invokes the /project/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/projects#api-method-project-new
    def self.project_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/project/new", input_params, opts)
    end

    # Invokes the /record-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-addtags
    def self.record_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /record-xxxx/addTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-addtypes
    def self.record_add_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTypes", input_params, opts)
    end

    # Invokes the /record-xxxx/close API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle#api-method-class-xxxx-close
    def self.record_close(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/close", input_params, opts)
    end

    # Invokes the /record-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/records#api-method-record-xxxx-describe
    def self.record_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /record-xxxx/getDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-getdetails
    def self.record_get_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/getDetails", input_params, opts)
    end

    # Invokes the /record-xxxx/listProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-listprojects
    def self.record_list_projects(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listProjects", input_params, opts)
    end

    # Invokes the /record-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-removetags
    def self.record_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /record-xxxx/removeTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-removetypes
    def self.record_remove_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTypes", input_params, opts)
    end

    # Invokes the /record-xxxx/rename API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/name#api-method-class-xxxx-rename
    def self.record_rename(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/rename", input_params, opts)
    end

    # Invokes the /record-xxxx/setDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-setdetails
    def self.record_set_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setDetails", input_params, opts)
    end

    # Invokes the /record-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/properties#api-method-class-xxxx-setproperties
    def self.record_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /record-xxxx/setVisibility API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/visibility#api-method-class-xxxx-setvisibility
    def self.record_set_visibility(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setVisibility", input_params, opts)
    end

    # Invokes the /record/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes/records#api-method-record-new
    def self.record_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/record/new", input_params, opts)
    end

    # Invokes the /system/describeDataObjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/system-methods#api-method-system-describedataobjects
    def self.system_describe_data_objects(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/describeDataObjects", input_params, opts)
    end

    # Invokes the /system/describeExecutions API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/system-methods#api-method-system-describeexecutions
    def self.system_describe_executions(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/describeExecutions", input_params, opts)
    end

    # Invokes the /system/describeProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/system-methods#api-method-system-describeprojects
    def self.system_describe_projects(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/describeProjects", input_params, opts)
    end

    # Invokes the /system/findAffiliates API method.
    def self.system_find_affiliates(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findAffiliates", input_params, opts)
    end

    # Invokes the /system/findApps API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-findapps
    def self.system_find_apps(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findApps", input_params, opts)
    end

    # Invokes the /system/findDataObjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-finddataobjects
    def self.system_find_data_objects(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findDataObjects", input_params, opts)
    end

    # Invokes the /system/findGlobalWorkflows API method.
    def self.system_find_global_workflows(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findGlobalWorkflows", input_params, opts)
    end

    # Invokes the /system/resolveDataObjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/system-methods#api-method-system-resolvedataobjects
    def self.system_resolve_data_objects(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/resolveDataObjects", input_params, opts)
    end

    # Invokes the /system/findExecutions API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-findexecutions
    def self.system_find_executions(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findExecutions", input_params, opts)
    end

    # Invokes the /system/findAnalyses API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-findanalyses
    def self.system_find_analyses(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findAnalyses", input_params, opts)
    end

    # Invokes the /system/findDatabases API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-finddatabases
    def self.system_find_databases(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findDatabases", input_params, opts)
    end

    # Invokes the /system/findJobs API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-findjobs
    def self.system_find_jobs(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findJobs", input_params, opts)
    end

    # Invokes the /system/findProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-findprojects
    def self.system_find_projects(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findProjects", input_params, opts)
    end

    # Invokes the /system/findUsers API method.
    def self.system_find_users(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findUsers", input_params, opts)
    end

    # Invokes the /system/findProjectMembers API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-findprojectmembers
    def self.system_find_project_members(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findProjectMembers", input_params, opts)
    end

    # Invokes the /system/findOrgs API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/search#api-method-system-findorgs
    def self.system_find_orgs(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/findOrgs", input_params, opts)
    end

    # Invokes the /system/generateBatchInputs API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/system-methods#api-method-system-generatebatchinputs
    def self.system_generate_batch_inputs(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/generateBatchInputs", input_params, opts)
    end

    # Invokes the /system/globalSearch API method.
    def self.system_global_search(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/globalSearch", input_params, opts)
    end

    # Invokes the /system/greet API method.
    def self.system_greet(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/greet", input_params, opts)
    end

    # Invokes the /system/headers API method.
    def self.system_headers(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/headers", input_params, opts)
    end

    # Invokes the /system/shortenURL API method.
    def self.system_shorten_url(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/shortenURL", input_params, opts)
    end

    # Invokes the /system/whoami API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/system-methods#api-method-system-whoamiwiki.
    def self.system_whoami(input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/system/whoami", input_params, opts)
    end

    # Invokes the /user-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/users#api-method-user-xxxx-describe
    def self.user_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /user-xxxx/update API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/users#api-method-user-xxxx-update
    def self.user_update(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/update", input_params, opts)
    end

    # Invokes the /workflow-xxxx/addStage API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-addstage
    def self.workflow_add_stage(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addStage", input_params, opts)
    end

    # Invokes the /workflow-xxxx/addTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-addtags
    def self.workflow_add_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTags", input_params, opts)
    end

    # Invokes the /workflow-xxxx/addTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-addtypes
    def self.workflow_add_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/addTypes", input_params, opts)
    end

    # Invokes the /workflow-xxxx/close API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle#api-method-class-xxxx-close
    def self.workflow_close(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/close", input_params, opts)
    end

    # Invokes the /workflow-xxxx/describe API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-describe
    def self.workflow_describe(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/describe", input_params, opts)
    end

    # Invokes the /workflow-xxxx/dryRun API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-dryrun
    def self.workflow_dry_run(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/dryRun", input_params, opts)
    end

    # Invokes the /workflow-xxxx/getDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-getdetails
    def self.workflow_get_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/getDetails", input_params, opts)
    end

    # Invokes the /workflow-xxxx/isStageCompatible API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-isstagecompatible
    def self.workflow_is_stage_compatible(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/isStageCompatible", input_params, opts)
    end

    # Invokes the /workflow-xxxx/listProjects API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-listprojects
    def self.workflow_list_projects(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/listProjects", input_params, opts)
    end

    # Invokes the /workflow-xxxx/moveStage API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-movestage
    def self.workflow_move_stage(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/moveStage", input_params, opts)
    end

    # Invokes the /workflow-xxxx/overwrite API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-overwrite
    def self.workflow_overwrite(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/overwrite", input_params, opts)
    end

    # Invokes the /workflow-xxxx/removeStage API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-removestage
    def self.workflow_remove_stage(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeStage", input_params, opts)
    end

    # Invokes the /workflow-xxxx/removeTags API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/tags#api-method-class-xxxx-removetags
    def self.workflow_remove_tags(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTags", input_params, opts)
    end

    # Invokes the /workflow-xxxx/removeTypes API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/types#api-method-class-xxxx-removetypes
    def self.workflow_remove_types(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/removeTypes", input_params, opts)
    end

    # Invokes the /workflow-xxxx/rename API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/name#api-method-class-xxxx-rename
    def self.workflow_rename(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/rename", input_params, opts)
    end

    # Invokes the /workflow-xxxx/run API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-run
    def self.workflow_run(object_id, input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/#{object_id}/run", input_params, opts)
    end

    # Invokes the /workflow-xxxx/validateBatch API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-validatebatch
    def self.workflow_validate_batch(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/validateBatch", input_params, opts)
    end

    # Invokes the /workflow-xxxx/setDetails API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/details-and-links#api-method-class-xxxx-setdetails
    def self.workflow_set_details(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setDetails", input_params, opts)
    end

    # Invokes the /workflow-xxxx/setProperties API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/introduction-to-data-object-metadata/properties#api-method-class-xxxx-setproperties
    def self.workflow_set_properties(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setProperties", input_params, opts)
    end

    # Invokes the /workflow-xxxx/setVisibility API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/data-object-lifecycle/visibility#api-method-class-xxxx-setvisibility
    def self.workflow_set_visibility(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/setVisibility", input_params, opts)
    end

    # Invokes the /workflow-xxxx/update API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-update
    def self.workflow_update(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/update", input_params, opts)
    end

    # Invokes the /workflow-xxxx/updateStageExecutable API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-xxxx-updatestageexecutable
    def self.workflow_update_stage_executable(object_id, input_params={}, opts={})
      opts = { "always_retry" => true }.merge(opts)
      return DX::http_request("/#{object_id}/updateStageExecutable", input_params, opts)
    end

    # Invokes the /workflow/new API method.
    #
    # For more info, see: https://documentation.dnanexus.com/developer/api/running-analyses/workflows-and-analyses#api-method-workflow-new
    def self.workflow_new(input_params={}, opts={})
      opts = { "always_retry" => false }.merge(opts)
      return DX::http_request("/workflow/new", input_params, opts)
    end

  end
end
