# Do not modify this file by hand.
#
# It is automatically generated by src/api_wrappers/generateRAPIWrappers.py.
# (Run make api_wrappers to update it.)


appAddCategories <- function(appNameOrID, alias=NULL,
                             inputParams=emptyNamedList, jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'addCategories', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appAddDevelopers <- function(appNameOrID, alias=NULL,
                             inputParams=emptyNamedList, jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'addDevelopers', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appAddTags <- function(appNameOrID, alias=NULL,
                       inputParams=emptyNamedList, jsonifyData=TRUE,
                       alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'addTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appDelete <- function(appNameOrID, alias=NULL,
                      inputParams=emptyNamedList, jsonifyData=TRUE,
                      alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'delete', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appDescribe <- function(appNameOrID, alias=NULL,
                        inputParams=emptyNamedList, jsonifyData=TRUE,
                        alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appGet <- function(appNameOrID, alias=NULL,
                   inputParams=emptyNamedList, jsonifyData=TRUE,
                   alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'get', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appInstall <- function(appNameOrID, alias=NULL,
                       inputParams=emptyNamedList, jsonifyData=TRUE,
                       alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'install', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appListCategories <- function(appNameOrID, alias=NULL,
                              inputParams=emptyNamedList, jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'listCategories', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appListDevelopers <- function(appNameOrID, alias=NULL,
                              inputParams=emptyNamedList, jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'listDevelopers', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appPublish <- function(appNameOrID, alias=NULL,
                       inputParams=emptyNamedList, jsonifyData=TRUE,
                       alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'publish', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appRemoveCategories <- function(appNameOrID, alias=NULL,
                                inputParams=emptyNamedList, jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'removeCategories', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appRemoveDevelopers <- function(appNameOrID, alias=NULL,
                                inputParams=emptyNamedList, jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'removeDevelopers', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appRemoveTags <- function(appNameOrID, alias=NULL,
                          inputParams=emptyNamedList, jsonifyData=TRUE,
                          alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'removeTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appRun <- function(appNameOrID, alias=NULL,
                   inputParams=emptyNamedList, jsonifyData=TRUE,
                   alwaysRetry=FALSE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'run', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appUninstall <- function(appNameOrID, alias=NULL,
                         inputParams=emptyNamedList, jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'uninstall', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appUpdate <- function(appNameOrID, alias=NULL,
                      inputParams=emptyNamedList, jsonifyData=TRUE,
                      alwaysRetry=TRUE) {
  if (is.null(alias)) {
    fullyQualifiedVersion <- paste('/', appNameOrID, sep='')
  } else {
    fullyQualifiedVersion <- paste('/', appNameOrID, '/', alias, sep='')
  }
  resource <- paste(fullyQualifiedVersion, '/', 'update', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData,
                alwaysRetry=alwaysRetry)
}


appNew <- function(inputParams=emptyNamedList,
                   jsonifyData=TRUE,
                   always_retry=FALSE) {
  dxHTTPRequest('/app/new', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


appletAddTags <- function(objectID,
                          inputParams=emptyNamedList,
                          jsonifyData=TRUE,
                          alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletAddTypes <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletClose <- function(objectID,
                        inputParams=emptyNamedList,
                        jsonifyData=TRUE,
                        alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'close', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletDescribe <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletGet <- function(objectID,
                      inputParams=emptyNamedList,
                      jsonifyData=TRUE,
                      alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'get', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletGetDetails <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'getDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletListProjects <- function(objectID,
                               inputParams=emptyNamedList,
                               jsonifyData=TRUE,
                               alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'listProjects', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletRemoveTags <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletRemoveTypes <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletRename <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'rename', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletRun <- function(objectID,
                      inputParams=emptyNamedList,
                      jsonifyData=TRUE,
                      alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'run', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletSetDetails <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletSetProperties <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setProperties', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletSetVisibility <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setVisibility', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


appletNew <- function(inputParams=emptyNamedList,
                      jsonifyData=TRUE,
                      always_retry=FALSE) {
  dxHTTPRequest('/applet/new', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


containerClone <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'clone', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerDescribe <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerDestroy <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'destroy', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerListFolder <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'listFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerMove <- function(objectID,
                          inputParams=emptyNamedList,
                          jsonifyData=TRUE,
                          alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'move', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerNewFolder <- function(objectID,
                               inputParams=emptyNamedList,
                               jsonifyData=TRUE,
                               alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'newFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerRemoveFolder <- function(objectID,
                                  inputParams=emptyNamedList,
                                  jsonifyData=TRUE,
                                  alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerRemoveObjects <- function(objectID,
                                   inputParams=emptyNamedList,
                                   jsonifyData=TRUE,
                                   alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeObjects', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


containerRenameFolder <- function(objectID,
                                  inputParams=emptyNamedList,
                                  jsonifyData=TRUE,
                                  alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'renameFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileAddTags <- function(objectID,
                        inputParams=emptyNamedList,
                        jsonifyData=TRUE,
                        alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileAddTypes <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileClose <- function(objectID,
                      inputParams=emptyNamedList,
                      jsonifyData=TRUE,
                      alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'close', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileDescribe <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileDownload <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'download', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileGetDetails <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'getDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileListProjects <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'listProjects', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileRemoveTags <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileRemoveTypes <- function(objectID,
                            inputParams=emptyNamedList,
                            jsonifyData=TRUE,
                            alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileRename <- function(objectID,
                       inputParams=emptyNamedList,
                       jsonifyData=TRUE,
                       alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'rename', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileSetDetails <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileSetProperties <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setProperties', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileSetVisibility <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setVisibility', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileUpload <- function(objectID,
                       inputParams=emptyNamedList,
                       jsonifyData=TRUE,
                       alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'upload', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


fileNew <- function(inputParams=emptyNamedList,
                    jsonifyData=TRUE,
                    always_retry=FALSE) {
  dxHTTPRequest('/file/new', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


gtableAddRows <- function(objectID,
                          inputParams=emptyNamedList,
                          jsonifyData=TRUE,
                          alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addRows', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableAddTags <- function(objectID,
                          inputParams=emptyNamedList,
                          jsonifyData=TRUE,
                          alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableAddTypes <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableClose <- function(objectID,
                        inputParams=emptyNamedList,
                        jsonifyData=TRUE,
                        alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'close', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableDescribe <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableGet <- function(objectID,
                      inputParams=emptyNamedList,
                      jsonifyData=TRUE,
                      alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'get', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableGetDetails <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'getDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableListProjects <- function(objectID,
                               inputParams=emptyNamedList,
                               jsonifyData=TRUE,
                               alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'listProjects', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableNextPart <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'nextPart', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableRemoveTags <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableRemoveTypes <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableRename <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'rename', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableSetDetails <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableSetProperties <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setProperties', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableSetVisibility <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setVisibility', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


gtableNew <- function(inputParams=emptyNamedList,
                      jsonifyData=TRUE,
                      always_retry=FALSE) {
  dxHTTPRequest('/gtable/new', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


jobDescribe <- function(objectID,
                        inputParams=emptyNamedList,
                        jsonifyData=TRUE,
                        alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


jobStreamLog <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'streamLog', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


jobTerminate <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'terminate', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


jobNew <- function(inputParams=emptyNamedList,
                   jsonifyData=TRUE,
                   always_retry=FALSE) {
  dxHTTPRequest('/job/new', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


notificationsGet <- function(inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             always_retry=TRUE) {
  dxHTTPRequest('/notifications/get', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


notificationsMarkRead <- function(inputParams=emptyNamedList,
                                  jsonifyData=TRUE,
                                  always_retry=TRUE) {
  dxHTTPRequest('/notifications/markRead', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


projectAddTags <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectClone <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'clone', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectDecreasePermissions <- function(objectID,
                                       inputParams=emptyNamedList,
                                       jsonifyData=TRUE,
                                       alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'decreasePermissions', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectDescribe <- function(objectID,
                            inputParams=emptyNamedList,
                            jsonifyData=TRUE,
                            alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectDestroy <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'destroy', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectInvite <- function(objectID,
                          inputParams=emptyNamedList,
                          jsonifyData=TRUE,
                          alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'invite', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectLeave <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'leave', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectListFolder <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'listFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectMove <- function(objectID,
                        inputParams=emptyNamedList,
                        jsonifyData=TRUE,
                        alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'move', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectNewFolder <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'newFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectRemoveFolder <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectRemoveObjects <- function(objectID,
                                 inputParams=emptyNamedList,
                                 jsonifyData=TRUE,
                                 alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeObjects', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectRemoveTags <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectRenameFolder <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'renameFolder', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectSetProperties <- function(objectID,
                                 inputParams=emptyNamedList,
                                 jsonifyData=TRUE,
                                 alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setProperties', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectSubscribe <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'subscribe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectUnsubscribe <- function(objectID,
                               inputParams=emptyNamedList,
                               jsonifyData=TRUE,
                               alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'unsubscribe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectUpdate <- function(objectID,
                          inputParams=emptyNamedList,
                          jsonifyData=TRUE,
                          alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'update', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


projectNew <- function(inputParams=emptyNamedList,
                       jsonifyData=TRUE,
                       always_retry=FALSE) {
  dxHTTPRequest('/project/new', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


recordAddTags <- function(objectID,
                          inputParams=emptyNamedList,
                          jsonifyData=TRUE,
                          alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordAddTypes <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'addTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordClose <- function(objectID,
                        inputParams=emptyNamedList,
                        jsonifyData=TRUE,
                        alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'close', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordDescribe <- function(objectID,
                           inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordGetDetails <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'getDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordListProjects <- function(objectID,
                               inputParams=emptyNamedList,
                               jsonifyData=TRUE,
                               alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'listProjects', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordRemoveTags <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTags', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordRemoveTypes <- function(objectID,
                              inputParams=emptyNamedList,
                              jsonifyData=TRUE,
                              alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'removeTypes', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordRename <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'rename', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordSetDetails <- function(objectID,
                             inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setDetails', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordSetProperties <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setProperties', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordSetVisibility <- function(objectID,
                                inputParams=emptyNamedList,
                                jsonifyData=TRUE,
                                alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'setVisibility', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


recordNew <- function(inputParams=emptyNamedList,
                      jsonifyData=TRUE,
                      always_retry=FALSE) {
  dxHTTPRequest('/record/new', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemFindAffiliates <- function(inputParams=emptyNamedList,
                                 jsonifyData=TRUE,
                                 always_retry=TRUE) {
  dxHTTPRequest('/system/findAffiliates', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemFindApps <- function(inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           always_retry=TRUE) {
  dxHTTPRequest('/system/findApps', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemFindDataObjects <- function(inputParams=emptyNamedList,
                                  jsonifyData=TRUE,
                                  always_retry=TRUE) {
  dxHTTPRequest('/system/findDataObjects', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemFindJobs <- function(inputParams=emptyNamedList,
                           jsonifyData=TRUE,
                           always_retry=TRUE) {
  dxHTTPRequest('/system/findJobs', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemFindProjects <- function(inputParams=emptyNamedList,
                               jsonifyData=TRUE,
                               always_retry=TRUE) {
  dxHTTPRequest('/system/findProjects', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemFindUsers <- function(inputParams=emptyNamedList,
                            jsonifyData=TRUE,
                            always_retry=TRUE) {
  dxHTTPRequest('/system/findUsers', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemFindProjectMembers <- function(inputParams=emptyNamedList,
                                     jsonifyData=TRUE,
                                     always_retry=TRUE) {
  dxHTTPRequest('/system/findProjectMembers', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


systemShortenURL <- function(inputParams=emptyNamedList,
                             jsonifyData=TRUE,
                             always_retry=TRUE) {
  dxHTTPRequest('/system/shortenURL', inputParams, jsonifyData=jsonifyData, alwaysRetry=alwaysRetry)
}


userDescribe <- function(objectID,
                         inputParams=emptyNamedList,
                         jsonifyData=TRUE,
                         alwaysRetry=TRUE) {
  resource <- paste('/', objectID, '/', 'describe', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}


userUpdate <- function(objectID,
                       inputParams=emptyNamedList,
                       jsonifyData=TRUE,
                       alwaysRetry=FALSE) {
  resource <- paste('/', objectID, '/', 'update', sep='')
  dxHTTPRequest(resource,
                inputParams,
                jsonifyData=jsonifyData,
                alwaysRetry=alwaysRetry)
}

