# -*- mode: Makefile -*-

# curl_build_dir := $(shell mktemp -d --tmpdir=/tmp curl-build-XXXXXX)

# curl:
# 	$(DNANEXUS_HOME)/src/ua/build_curl.sh $(curl_build_dir)

GITVERSION := $(shell git describe)

curl_dir = /home/jdale/sw/local
cpp_dir = $(DNANEXUS_HOME)/src/cpp
dxjson_dir = $(cpp_dir)/dxjson
dxhttp_dir = $(cpp_dir)/SimpleHttpLib
dxcpp_dir = $(cpp_dir)/dxcpp
ua_dir = $(DNANEXUS_HOME)/src/ua

VPATH = $(dxjson_dir):$(dxhttp_dir):$(dxcpp_dir):$(ua_dir)

CXXFLAGS = -g -D_FILE_OFFSET_BITS=64 -DGITVERSION=\"$(GITVERSION)\" -Wall -Wextra -Werror=return-type -std=c++0x -I$(curl_dir)/include -I$(cpp_dir) -I$(dxhttp_dir) -I$(dxjson_dir) -I$(dxcpp_dir)
LDFLAGS := -static -pthread -L/usr/lib -L$(curl_dir)/lib -lcurl -lcares -lssl -lcrypto -lrt -lz -ldl -lboost_program_options-mt -lboost_filesystem -lboost_system -lboost_thread-mt -lboost_regex

dxjson_objs = dxjson.o
dxhttp_objs = SimpleHttp.o SimpleHttpHeaders.o Utility.o
dxcpp_objs = api.o bindings.o dxcpp.o
ua_objs = chunk.o main.o options.o SSLThreads.o

dxjson: $(dxjson_objs)
dxhttp: $(dxhttp_objs)
dxcpp: $(dxcpp_objs)
ua: $(ua_objs)

all: dxjson dxhttp dxcpp ua
	g++ *.o $(LDFLAGS) -o ua 

clean:
	rm -v *.o ua

.PHONY: all dxjson dxhttp dxcpp ua
