# -*- mode: Makefile -*-
#
# Copyright (C) 2013 DNAnexus, Inc.
#
# This file is part of dx-toolkit (DNAnexus platform client libraries).
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may not
#   use this file except in compliance with the License. You may obtain a copy
#   of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

# curl_build_dir := $(shell mktemp -d --tmpdir=/tmp curl-build-XXXXXX)

# curl:
# 	$(DNANEXUS_HOME)/src/ua/build_curl.sh $(curl_build_dir)
UNAME := $(shell uname)

ifneq ($(UNAME), MINGW32_NT-6.1)
	$(error This Makefile should be used only with MINGW32_NT-6.1)
endif

DXTOOLKIT_GITVERSION := $(shell git describe)

sw_dir = $(HOME)/sw/local
curl_dir = $(sw_dir)/curl
cpp_dir = $(DNANEXUS_HOME)/src/cpp
dxjson_dir = $(cpp_dir)/dxjson
dxhttp_dir = $(cpp_dir)/SimpleHttpLib
dxcpp_dir = $(cpp_dir)/dxcpp
ua_dir = $(DNANEXUS_HOME)/src/ua
zlib_dir = $(sw_dir)/zlib-1.2.3-lib
lmagic_dir = $(sw_dir)/file-5.03-lib
boost_dir = $(sw_dir)/boost_1_51_0
VPATH = $(dxjson_dir):$(dxhttp_dir):$(dxcpp_dir):$(ua_dir)
# Note we use the -std=gnu++0x flag instead of c++0x for Windows compilation, because
# c++0x mode turns on the __STRICT_ANSI__ flag, which forbids functions such as fseeko64() (which we use)

CFLAGS = -O3 -Wall -pedantic -Wextra -I/include -I$(zlib_dir)/include -I$(lmagic_dir)/include
CXXFLAGS = -DWINDOWS_BUILD=1 -DBOOST_THREAD_USE_LIB -D_FILE_OFFSET_BITS=64 -DUAVERSION=\"$(VERSION)\" -DDXTOOLKIT_GITVERSION=\"$(DXTOOLKIT_GITVERSION)\" -O3 -Wall -pedantic -Wextra -Werror=return-type -Wno-switch -std=gnu++0x -I$(curl_dir)/include -I$(cpp_dir) -I$(dxhttp_dir) -I$(dxjson_dir) -I$(dxcpp_dir) -I$(ua_dir) -I$(boost_dir) -I$(zlib_dir)/include -I$(lmagic_dir)/include -I/include

LDFLAGS := -static-libstdc++ -static-libgcc -DBOOST_THREAD_USE_LIB -L$(boost_dir)/stage/lib -L$(curl_dir)/lib -L/lib -L$(lmagic_dir)/lib $(LDFLAGS) -L$(zlib_dir)/lib -lboost_program_options-mgw47-mt-1_51 -lboost_filesystem-mgw47-mt-1_51 -lboost_regex-mgw47-mt-1_51 -lboost_system-mgw47-mt-1_51 -lcurl -lcrypto -lmagic -lz -lboost_thread-mgw47-mt-1_51 -lboost_chrono-mgw47-mt-1_51

dxjson_objs = dxjson.o
dxhttp_objs = SimpleHttp.o SimpleHttpHeaders.o Utility.o
dxcpp_objs = api.o dxcpp.o SSLThreads.o utils.o dxlog.o 
ua_objs = compress.o options.o chunk.o main.o file.o api_helper.o import_apps.o mime.o round_robin_dns.o

dxjson: $(dxjson_objs)
dxhttp: $(dxhttp_objs)
dxcpp: $(dxcpp_objs)
ua: $(ua_objs)

all: dxjson dxhttp dxcpp ua
	g++ *.o $(LDFLAGS) -o ua

dist: all
	rm -rf ua-$(VERSION)-windows ua-$(VERSION)-windows.zip
	mkdir -p ua-$(VERSION)-windows
	mv ua.exe ua-$(VERSION)-windows/
	../windows_build/collect_ua_dlls.sh ua-$(VERSION)-windows
	cd ua-$(VERSION)-windows && zip -9 -r ../ua-$(VERSION)-windows.zip .
	rm -rf ua-$(VERSION)-windows
clean:
	rm -v *.o ua

.PHONY: all dxjson dxhttp dxcpp ua
