# Copyright (C) 2013-2016 DNAnexus, Inc.
#
# This file is part of dx-toolkit (DNAnexus platform client libraries).
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may not
#   use this file except in compliance with the License. You may obtain a copy
#   of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

$(DNANEXUS_HOME)/bin/dx: $(shell find python/{dxpy,scripts,requirements*,setup*} -not -name toolkit_version*)
	python3 -c 'import sys; exit("dx-toolkit is not compatible with Python < 3.8" if sys.version_info < (3, 8) else 0)'
	rm -rf "$(DX_PY_ENV)" python/dist
	$(VIRTUAL_ENV) "$(DX_PY_ENV)"

	unset PYTHONPATH; source "$(DX_PY_ENV)/$(ACTIVATE)"; ${PIP} install --upgrade -r python/requirements_setuptools.txt

	# Build the dxpy wheel and move it into place
	unset PYTHONPATH; source "$(DX_PY_ENV)/$(ACTIVATE)"; ls -l; ${PIP} install python/

# System dependencies
# ===================

install_sysdeps:
	echo "no dependencies for mac osx"
