name: dxpy-deptests

on:
  workflow_dispatch:

  pull_request:

jobs:
  dxpy-deptests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          docker --version
          docker-compose --version
          pip3 install docker
