name: toolkit-build-ubuntu-22.04

on:
  workflow_dispatch:

  pull_request:

jobs:
  toolkit-build-ubuntu-22.04:
    runs-on: ubuntu-22.04
    steps:
      - name: dx-toolkit python make target
        run: |
          make python
