name: toolkit-build-ubuntu-2204

on:
  workflow_dispatch:

  pull_request:

jobs:
  toolkit-build-ubuntu-2204:
    runs-on: ubuntu-22.04
    steps:
      - name: dx-toolkit python make target
        run: |
          make python
