name: toolkit-build-ubuntu-2204

on:
  workflow_dispatch:

  pull_request:

jobs:
  toolkit-build-ubuntu-2204:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: DEBUG
        run: |
          pwd
          #source environment
          #echo $DNANEXUS_HOME
          apt-get update && apt-get install -y build-essential
          make toolkit_version
          #ls -1R /__w/dx-toolkit/dx-toolkit
          ls -la /__w/dx-toolkit/dx-toolkit/build/info
          cat /__w/dx-toolkit/dx-toolkit/src/../build/info/version

      - name: Install build dependencies
        run: |
          apt-get update && apt-get install -y \
            git python-is-python3 python3-venv python3-dev \
            libssl-dev libffi-dev flex bison build-essential cmake \
            libboost-all-dev curl libcurl4-openssl-dev

      - name: Python make target
        run: |
          make python
          cat build/info/version

      - name: Build verification test
        run: |
          source environment
          dx --version

      - name: Default make target
        run: |
          make 
          source environment
          dx-verify-file --version
