name: toolkit-build-ubuntu-2204

on:
  workflow_dispatch:

  pull_request:

jobs:
  toolkit-build-ubuntu-2204:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    defaults:
      run:
        shell: bash
    steps:
      # git must be in the PATH before checkout, so that the checkout
      # action creates a local git repo with a .git/ dir. Without this
      # the checkout action doesn't create the .git dir, which causes
      # problems building dx-verify-file. See:
      # https://github.com/actions/checkout/issues/335
      - name: Install git before checkout
        run: |
          apt-get update && apt-get install -y git
          # Workaround for https://github.com/actions/runner/issues/2033
          git config --global --add safe.directory /__w/dx-toolkit/dx-toolkit

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for src/python/setup.py to function
        #  #set-safe-directory: true # Doesn't seem to work in a container

      #- name: DEBUG
      #  run: |
      #    pwd
      #    apt-get update && apt-get install -y build-essential python-is-python3 python3-venv python3-dev
      #    source environment
      #    echo $DNANEXUS_HOME
      #    echo "Git contents"
      #    ls -la $DNANEXUS_HOME/.git
      #    make toolkit_version
      #    echo "contents of /__w/dx-toolkit/dx-toolkit/src/../build/info/version"
      #    cat /__w/dx-toolkit/dx-toolkit/src/../build/info/version
      #    echo "contents of /__w/dx-toolkit/dx-toolkit/src/python/dxpy/toolkit_version.py"
      #    cat /__w/dx-toolkit/dx-toolkit/src/python/dxpy/toolkit_version.py

      - name: Install build dependencies
        run: |
          apt-get install -y \
            python-is-python3 python3-venv python3-dev \
            libssl-dev libffi-dev flex bison build-essential cmake \
            libboost-all-dev curl libcurl4-openssl-dev

      - name: Default make target
        run: |
          source environment
          make 

      - name: Build verification test
        run: |
          source environment
          dx --version
          dx-verify-file --version

      #- name: Python make target
      #  run: |
      #    make python
      #    cat build/info/version
