name: toolkit-build-ubuntu-2204

on:
  workflow_dispatch:

  pull_request:

jobs:
  toolkit-build-ubuntu-2204:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: python make target
        run: |
          apt-get update && apt-get install -y \
            python-is-python3 python3-venv python3-dev \
            libssl-dev libffi-dev flex bison build-essential cmake \
            libboost-all-dev curl libcurl4-openssl-dev
          make python
