name: toolkit-build-ubuntu-2204

on:
  workflow_dispatch:

  pull_request:

jobs:
  toolkit-build-ubuntu-2204:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: python make target
        run: |
          make python
